### ISSUE TITLE
Video thumbnail failed to save

### ISSUE THREAD

**Issue by TomLewis** [dustinscarberry/utubevideogallery#1]
All of a sudden when I try to add a new video it says “Video thumbnail failed to save”

**Comment by dustinscarberry** [comment]
> All of a sudden when I try to add a new video it says “Video thumbnail failed to save”

What version of WordPress, PHP, GD, Imagick are you currently using?

**Comment by TomLewis** [comment]
No idea why anyone would run an old version of wordpress, but either way V5.1
PHP Version 7.2
Plugin Version: 2.0.2
ImageMagick & GD both have ticks next to them in the plugin, no idea how to check their versions.

My report on the wordpress forums, another person is having the same issue.

**Comment by dustinscarberry** [comment]
Currently looking into the issue.

**Comment by dustinscarberry** [comment]
@FrozenBeard I'm having issues narrowing down the exact error your having. Would it be possible to provide a testing WordPress blog to debug against?

**Comment by dustinscarberry** [comment]
@FrozenBeard Can you ensure that you have a YouTube API Key set in the settings panel?

**Comment by TomLewis** [comment]
The API fixed it, thank you!
